import React, {useEffect, useState} from 'react';
import type {User} from '@supabase/supabase-js';
import {supabase} from './supabase';
import {createRoot} from 'react-dom/client';
import './style.css';
type Card={id:string;deck:string;front:string;back:string;streak:number;mastered:boolean;attempts:number};
const KEY='my-flashcards-mastery-v1';
const DECKS_KEY='my-flashcards-decks-v1';
function loadDecks():string[]{try{const value=JSON.parse(localStorage.getItem(DECKS_KEY)||'[]');return Array.isArray(value)?value.filter((d):d is string=>typeof d==='string'&&!!d.trim()):[]}catch{return []}}
function load():Card[]{try{const data=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(data)?data.filter(c=>typeof c.id==='string'&&typeof c.front==='string'&&typeof c.back==='string'&&typeof c.deck==='string'&&typeof c.streak==='number'&&typeof c.mastered==='boolean'):[]}catch{return []}}
function App(){
 const [user,setUser]=useState<User|null>(null);
 const [authReady,setAuthReady]=useState(false);
 const [email,setEmail]=useState('');
 const [password,setPassword]=useState('');
 const [authMessage,setAuthMessage]=useState('');
 const [authBusy,setAuthBusy]=useState(false);
 useEffect(()=>{if(!supabase){setAuthMessage('Set up .env.local using .env.example.');setAuthReady(true);return;}void supabase.auth.getUser().then(({data,error})=>{setUser(data.user);if(error)setAuthMessage(error.message);setAuthReady(true)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>setUser(session?.user??null));return()=>subscription.unsubscribe()},[]);
 async function authenticate(mode:'signIn'|'signUp'){if(!supabase)return;setAuthBusy(true);const result=mode==='signIn'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});setAuthBusy(false);setPassword('');setAuthMessage(result.error?.message??(mode==='signUp'?'Account created. Confirm your email if required.':'Signed in.'));}

 const [cards,setCards]=useState<Card[]>(load);
 const [savedDecks,setSavedDecks]=useState<string[]>(loadDecks);
 const [newDeck,setNewDeck]=useState('');
 const [deck,setDeck]=useState(()=>localStorage.getItem('my-flashcards-last-deck')||'General'),[front,setFront]=useState(''),[back,setBack]=useState('');
 const [activeDeck,setActiveDeck]=useState('All'),[flipped,setFlipped]=useState(false),[message,setMessage]=useState(''),[practiceMastered,setPracticeMastered]=useState(false);
 const [queue,setQueue]=useState<string[]>([]);
 function save(next:Card[]){setCards(next);localStorage.setItem(KEY,JSON.stringify(next))}
 const availableDecks=[...new Set(['General',...savedDecks,...cards.map(c=>c.deck)])];
 const decks=['All',...availableDecks];
 function chooseDeck(value:string){setDeck(value);localStorage.setItem('my-flashcards-last-deck',value)}
 function createDeck(e:React.FormEvent){e.preventDefault();const name=newDeck.trim();if(!name)return;if(availableDecks.some(d=>d.toLowerCase()===name.toLowerCase())){setMessage('That deck already exists');return}const next=[...savedDecks,name];setSavedDecks(next);localStorage.setItem(DECKS_KEY,JSON.stringify(next));chooseDeck(name);setActiveDeck(name);setNewDeck('');setFlipped(false);setQueue([]);setMessage('Deck created and selected for new cards')}
 const eligible=cards.filter(c=>(activeDeck==='All'||c.deck===activeDeck)&&(practiceMastered?c.mastered:!c.mastered));
 const ordered=[...eligible].sort((a,b)=>{const ai=queue.indexOf(a.id),bi=queue.indexOf(b.id);if(ai>=0||bi>=0)return (ai<0?999999:ai)-(bi<0?999999:bi);return a.streak-b.streak});
 const current=ordered[0];
 function add(e:React.FormEvent){e.preventDefault();if(!front.trim()||!back.trim()||!deck.trim())return;save([...cards,{id:crypto.randomUUID(),deck:deck.trim(),front:front.trim(),back:back.trim(),streak:0,mastered:false,attempts:0}]);setFront('');setBack('');setMessage('Card added')}
 function review(grade:'again'|'good'|'easy') {if(!current)return;const streak=grade==='again'?0:current.streak+(grade==='easy'?2:1);const mastered=practiceMastered?current.mastered:streak>=4;save(cards.map(c=>c.id===current.id?{...c,streak,mastered,attempts:c.attempts+1}:c));setQueue(prev=>[...prev.filter(id=>id!==current.id),...(!mastered?[current.id]:[])]);setFlipped(false);setMessage(mastered&&!practiceMastered?'Word mastered!':'Progress saved on this device')}
 function exportCards(){const url=URL.createObjectURL(new Blob([JSON.stringify(cards,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='flashcards-backup.json';a.click();URL.revokeObjectURL(url)}
 async function importCards(file:File){try{const raw=JSON.parse(await file.text());if(!Array.isArray(raw)||!raw.every(c=>typeof c.id==='string'&&typeof c.deck==='string'&&typeof c.front==='string'&&typeof c.back==='string'&&Number.isInteger(c.streak)&&c.streak>=0&&typeof c.mastered==='boolean'&&Number.isInteger(c.attempts)&&c.attempts>=0))throw Error('Invalid file');const merged=new Map(cards.map(c=>[c.id,c]));raw.forEach((c:Card)=>merged.set(c.id,c));save([...merged.values()]);setMessage('Backup imported')}catch{setMessage('Invalid mastery backup file')}}
 if(!authReady)return <main><p>Loading…</p></main>;
 if(!user)return <main><header><h1>Flashy</h1><p>Sign in to your account.</p></header><section><h2>Account</h2><form onSubmit={e=>{e.preventDefault();void authenticate('signIn')}}><label>Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" minLength={6} required value={password} onChange={e=>setPassword(e.target.value)}/></label><div className="actions"><button disabled={authBusy||!supabase} type="submit">Sign in</button><button disabled={authBusy||!supabase} type="button" onClick={()=>void authenticate('signUp')}>Create account</button></div></form>{authMessage&&<p role="status">{authMessage}</p>}</section></main>;
 return <main><header><h1>Flashy</h1><p>Learn at your own pace. No scheduled reviews. Cards still stay on this device while cloud synchronization is being developed.</p><p>Signed in as {user.email} <button onClick={()=>void supabase?.auth.signOut()}>Sign out</button></p></header><section className="stats"><span>{cards.length} total cards</span><span>{cards.filter(c=>c.mastered).length} mastered</span><span>{cards.filter(c=>!c.mastered).length} learning</span></section><section><h2>Study</h2><label>Deck <select value={activeDeck} onChange={e=>{setActiveDeck(e.target.value);if(e.target.value!=='All')chooseDeck(e.target.value);setFlipped(false);setQueue([])}}>{decks.map(d=><option key={d}>{d}</option>)}</select></label><label className="check"><input type="checkbox" checked={practiceMastered} onChange={e=>{setPracticeMastered(e.target.checked);setQueue([]);setFlipped(false)}}/> Practice mastered words</label>{current?<><button className="flashcard" onClick={()=>setFlipped(!flipped)}><small>{flipped?'ANSWER':'QUESTION'} · {current.deck}</small><strong>{flipped?current.back:current.front}</strong><small>Tap to flip · {current.streak}/4 mastery points</small></button>{flipped&&<div className="actions"><button onClick={()=>review('again')}>Again</button><button onClick={()=>review('good')}>Got it</button><button onClick={()=>review('easy')}>Easy</button></div>}</>:<p>{practiceMastered?'No mastered words in this deck yet.':'All words in this deck are mastered, or you have not added any yet!'}</p>}</section><section><h2>Create a deck</h2><form onSubmit={createDeck}><label>New deck name<input value={newDeck} maxLength={80} onChange={e=>setNewDeck(e.target.value)} placeholder="e.g. Genki Chapter 1" required/></label><button type="submit">Create deck</button></form></section><section><h2>Add a card</h2><form onSubmit={add}><label>Deck<select value={deck} onChange={e=>chooseDeck(e.target.value)}>{availableDecks.map(d=><option key={d} value={d}>{d}</option>)}</select></label><label>Term<input value={front} maxLength={500} onChange={e=>setFront(e.target.value)} required/></label><label>Definition<textarea value={back} maxLength={3000} onChange={e=>setBack(e.target.value)} required/></label><button type="submit">Add card</button></form></section><section><h2>Backups</h2><div className="actions"><button onClick={exportCards}>Export JSON</button><label className="import">Import JSON<input type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void importCards(f);e.target.value=''}}/></label></div><p className="hint">Export backups regularly. This version does not sync across devices yet.</p></section>{message&&<p role="status">{message}</p>}</main>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
